# Лекция 5. Метод канонических корреляций

## Суть метода


Канонические  корреляции - это расширение парной корреляции на случай, когда имеется несколько результативных показателей $W$ и нескольких влияющих факторов $P$.

В каноническом анализе матрица значений исходных переменных имеет вид:

| Объект анализа | Результативные показатели | Влияющие факторы |
|----------------|---------------------------|------------------|
|                | $W_1$    $W_2$   $\ldots$   $W_m$|$P_1$ $P_2$ $\ldots$ $P_n$|
|$O_1$           |$w_{11}$  $w_{12}$ $\ldots$  $w_{1m}$|$p_{11}$  $p_{12}$ $\ldots$  $p_{1n}$|
|$O_2$           |$w_{21}$  $w_{22}$ $\ldots$  $w_{2m}$|$p_{21}$  $p_{22}$ $\ldots$  $p_{2n}$|
|$O_3$           |$w_{31}$  $w_{32}$ $\ldots$  $w_{3m}$|$p_{31}$  $p_{32}$ $\ldots$  $p_{3n}$|
|...|...|...|
|$O_k$           |$w_{k1}$  $w_{k2}$ $\ldots$  $w_{km}$|$p_{k1}$  $p_{k2}$ $\ldots$  $p_{kn}$|


Таким образом, возникает задача исследования относительной связи между двумя группами параметров, заданных матрицами  $P$ и  $W$:
 $$P=\left(\begin{matrix}p_{1,1}&p_{1,2}&\ldots&p_{1,n}\\p_{2,1}&p_{2,2}&\ldots &p_{2,n}\\\ldots &\ldots &\ldots&\ldots \\p_{k,1}&p_{k,2}&\ldots &p_{k,n}\end{matrix}\right),$$
 \begin{eqnarray}\label{m_f1}W=\left(\begin{matrix}w_{1,1}&w_{1,2}&\ldots&w_{1,m}\\w_{2,1}&w_{2,2}&\ldots &w_{2,m}\\\ldots &\ldots &\ldots&\ldots \\w_{k,1}&w_{k,2}&\ldots &w_{k,m}\end{matrix}\right),\end{eqnarray}
где  $k$ - размер выборки;  $n$ - количество влияющих факторов; $m$ - количество результативных показателей.

Основная задача метода  - построить некоторые новые синтетические показатели - **канонические переменные**, как линейные комбинации от искомых переменных. Причем эти линейные комбинации составляются так, чтобы между каноническими переменными была максимальная парная корреляция.

Канонические корреляции используются для научного обоснования системы показателей при проведении многомерного статистического анализа, подборе групп влияющих показателей.

## Некоторые сведения из теории вероятностей и линейной алгебры

1. Пусть $X,Y$ - две случайные величины. Ковариация между $X$ и $Y$ определяется как:
    $$cov(X,Y)=M((X-M(X))\cdot (Y-M(Y)))$$
    $$M((X-M(X))\cdot (Y-M(Y)))=M(XY-XM(Y)-YM(X)+M(X)M(Y))=M(XY)-M(X)M(Y)-M(Y)M(X)+M(X)M(Y)=M(XY)-M(X)M(Y)$$
    $$cov(X,Y)=M(XY)-M(X)M(Y)$$
2. Линейный коэффициент корреляции:
$$\rho=\frac{M(XY)-M(X)M(Y)}{\sigma_X\sigma_Y}=\frac{cov(X,Y)}{\sigma_X\sigma_Y}$$
3. Если $M(X)=M(Y)=0$, то $cov(X,Y)=M(X\cdot Y)$

Если $Q$ - матрица столбцов стандартизированных случайных величин $q_1,q_2,\ldots, q_n$ (с нулевым математическим ожиданием и единичной дисперсией каждая), то корреляционная матрица (она же в этом случае и ковариационная) от $Q$ равна:
$$cor(Q)=cov(Q)=\frac{1}{n}\cdot \left(Q^T\cdot Q\right)$$
Если $A,B$ - две матрицы стандартизованных случайных величин размерности $m\cdot n$, $m\cdot n$ соответственно, кросс-корреляционная матрица определяется как:
$$cov(A,B)=A^T\cdot B$$
4. Математическое ожидание произведения двух зависимых случайных величин равно:
$$M(XY)=M(X)M(Y)+\rho\cdot \sigma_X\sigma_Y$$
5. Если $X$ - случайная величина с нулевым математическим ожиданием, то:
$$D(X)=M((X-M(X))^2)=M(X^2)=cov(X,X)$$
6. Для квадратных матриц  $A$,   $B$ одинаковой размерности справедливо:
$$A\cdot B^T=(B\cdot A^T)^T$$
$$\left(AB\right)^T=B^T\cdot A^T$$


In [3]:
import numpy as np
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print("A=",A)
B=np.matrix([[5,6,7],[8,9,10]])
print("B=",B)

print(np.dot(A,np.transpose(B)))

print(np.transpose(np.dot(B,np.transpose(A))))

A= [[1 2 3]
 [4 5 6]
 [7 8 9]]
B= [[ 5  6  7]
 [ 8  9 10]]
[[ 38  56]
 [ 92 137]
 [146 218]]
[[ 38  56]
 [ 92 137]
 [146 218]]


In [41]:
np.transpose(np.dot(B, A))

matrix([[ 78, 114],
        [ 96, 141],
        [114, 168]])

In [42]:
np.dot(np.transpose(A),np.transpose(B))

matrix([[ 78, 114],
        [ 96, 141],
        [114, 168]])

7. Пусть задана некоторая квадратная матрица $Q$ размерностью $n\cdot n$, если выполняется соотношение:
$$Q\cdot X=\alpha X$$
где $X$ - некоторый вектор столбец размерностью $n$, $\alpha$ - некоторое число, 

то вектор $X$ называется собственным вектором матрицы $Q$, $\alpha$ - собственным значением матрицы $Q$.

Рассмотрим на примере.

Пусть $$Q=\left(\begin{matrix} -1 & -6 \\ 
                               2 & 6 
               \end{matrix}\right)$$
Тогда получаем:

$$\left(\begin{matrix} -1 & -6 \\ 
                               2 & 6 
               \end{matrix}\right)\cdot \left(\begin{matrix} x_1 \\ x_2
               \end{matrix}\right)=\alpha\cdot \left(\begin{matrix} x_1 \\ x_2
               \end{matrix}\right)$$
Приходим к системе уравнений:
$$
\begin{equation*}
 \begin{cases}
   -1x_1-6x_2=\alpha x_1
   \\
   2x_1+6x_2=\alpha x_2
 \end{cases}
\end{equation*}
$$
$$
\begin{equation*}
 \begin{cases}
   (-1-\alpha)x_1-6x_2=0
   \\
   2x_1+(6-\alpha)x_2=0
 \end{cases}
\end{equation*}
$$
Поскольку по определению собственных векторов, нас не устраивают нулевые решения, то 
нужно искать линейно зависимые решения (т.е. условие равенства нулю главного определителя системы уравнений):
$$\left(\begin{matrix} -1-\alpha & -6 \\ 
                               2 & 6-\alpha 
               \end{matrix}\right)=0\Rightarrow \alpha^2-5\alpha+12=0$$
$$\alpha_1=2, \alpha_2=3$$ 
Найдем собственные вектора:
$$
\begin{equation*}
 \begin{cases}
   (-1-2)x_1-6x_2=0
   \\
   2x_1+(6-2)x_2=0
 \end{cases}
\end{equation*}\Rightarrow x_1=-2x_2
$$
$$
\begin{equation*}
 \begin{cases}
   (-1-3)x_1-6x_2=0
   \\
   2x_1+(6-3)x_2=0
 \end{cases}
\end{equation*}\Rightarrow x_1=-\frac{3}{2}x_2
$$
Выберем ортонормированную систему векторов:
$$\overline{x_1}=\frac{x_1}{\sqrt{x_1^2+x_2^2}}, \overline{x_2}=\frac{x_2}{\sqrt{x_1^2+x_2^2}}$$
$$\overline{x_1}=\frac{-2x_2}{\sqrt{4x_2^2+x_2^2}}=\frac{-2}{\sqrt{5}}=-0.8944271909999159,$$
$$\overline{x_2}=\frac{x_2}{\sqrt{4x_2^2+x_2^2}}=\frac{1}{\sqrt{5}}=0.4472135954999579$$
Аналогично находится второй собственный вектор.

В python для получения собственных векторов и собственных значений используют библиотеку numpy:

In [17]:
import numpy as np
Q=np.matrix([[-1,-6],[2,6]])
R=np.linalg.eig(Q)
R

(array([2., 3.]),
 matrix([[-0.89442719,  0.83205029],
         [ 0.4472136 , -0.5547002 ]]))

Проведем проверки:

In [27]:
print(np.dot(Q,R[1][:,0]))
print(R[0][0]*R[1][:,0])

[[-1.78885438]
 [ 0.89442719]]
[[-1.78885438]
 [ 0.89442719]]


In [28]:
print(np.dot(Q,R[1][:,1]))
print(R[0][1]*R[1][:,1])

[[ 2.49615088]
 [-1.66410059]]
[[ 2.49615088]
 [-1.66410059]]


## Теоретическое обоснование метода

Если для  $j$-го объекта анализа множество влияющих факторов представлено значениями $\{p_{j,1},p_{j,2},\ldots p_{j,n}\}$, а множество результативных показателей представлено значениями  $\{w_{j,1},w_{j,2},\ldots w_{j,m}\}$, то значения канонических переменных для  $j$-го объекта определяются в виде:
\begin{equation*}
u_{j}=\alpha _{1}\cdot p_{j,1}+\alpha _{2}\cdot p_{j,2}+\ldots +\alpha_{n}\cdot p_{j,n}
\end{equation*}
 $$v_{j}=\beta _{1}\cdot w_{j,1}+\beta _{2}\cdot w_{j,2}+\ldots +\beta_{m}\cdot w_{j,m},$$
что в матричной форме для всех  $k$ объектов анализа может быть представлено в виде:
 \begin{eqnarray}\label{m_f2}U=\alpha \cdot P^{T}, V=\beta \cdot W^{T},\end{eqnarray}
где  $U=(u_{1},u_{2},\ldots ,u_{k})$,  $V=(v_{1},v_{2},\ldots ,v_{k})$ - полученные векторы канонических переменных, $P^{T},W^{T}$ - соответствующие транспонированные матрицы, $\alpha=(\alpha _{1}, \alpha _{2}, \ldots, \alpha _{n}), \beta=(\beta _{1}, \beta _{2}, \ldots, \beta_{m})$

Если рассматривать  $U=(u_{1},u_{2},\ldots ,u_{k})$  и  $V=(v_{1},v_{2},\ldots ,v_{k})$  как реализации двух случайных величин  $u,v$, то задача сводится к нахождению значений коэффициентов линейных комбинаций  $\alpha$  и  $\beta$, так, чтобы обеспечить максимальную корреляцию между  $u,v$.

Перед проведением расчетов, как правило, выполняется стандартизация исходных переменных множеств $\{p_{1,}p_{2,}\ldots p_{n}\}$ и  $\{w_{1},w_{2},\ldots w_{m}\}$ в виде:
\begin{equation*}
\tilde{p}_{h,i}=\frac{p_{h,i}-M(p_{i})}{\sigma _{p_{i}}}
\end{equation*}
 \begin{eqnarray}\label{m_f3}{\tilde {{w}}}_{h,j}=\frac{w_{h,j}-M(w_{j})}{\sigma _{w_{j}}},\end{eqnarray}
где  $M(p_{i}),M(w_{j})$ - средние значения  $p_{i},w_{j}$ на выборке соответственно; $\sigma _{p_{i}},\sigma _{w_{j}}$ - стандартные отклонения $p_{i},w_{j}$  на выборке соответственно.

Тогда канонические переменные для каждого  $j$-го объекта определяют в виде: 
\begin{equation*}
u_{j}=\alpha _{1}\cdot {\tilde {{p}}}_{j,1}+\alpha _{2}\cdot {\tilde{{p}}}_{j,2}+\ldots +\alpha _{n}\cdot {\tilde {{p}}}_{j,n}
\end{equation*}
 $$v_{j}=\beta _{1}\cdot {\tilde {{w}}}_{j,1}+\beta _{2}\cdot {\tilde{{w}}}_{j,2}+\ldots +\beta _{m}\cdot {\tilde {{w}}}_{j,m},$$
поэтому как легко заметить:
 $$M(U)=M(\alpha _{1}\cdot {\tilde {{p}}}_{1}+\alpha _{2}\cdot {\tilde{{p}}}_{2}+\ldots +\alpha _{n}\cdot \tilde {{p_{n}}})=\alpha _{1}\cdot M(\tilde {{p_{1}}})+\alpha _{2}\cdot M(\tilde {{p_{2}}})+\ldots +\alpha_{n}\cdot M(\tilde {{p_{n}}})$$
$$M(U)=0$$
$$M(V)=M(\beta _{1}\cdot \tilde {{w_{1}}}+\beta _{2}\cdot \tilde{{w_{2}}}+\ldots +\beta _{m}\cdot \tilde {{w_{m}}})=\beta _{1}\cdot M(\tilde {{w_{1}}})+\beta _{2}\cdot M(\tilde {{w_{2}}})+\ldots +\beta_{m}\cdot M(\tilde {{w_{m}}})$$
$$M(V)=0$$

Для интерпретации канонических переменных оценим случайную величину  $U$ в виде  $a\cdot V$ (т.е. оценим линейную связь между $U$ и $V$).

Найдем среднюю квадратичную ошибку такого приближения:
 \begin{eqnarray}\label{m_f4}M((U-a\cdot U)^{2})=\sigma _{u}^{2}-2\cdot a\cdot \sigma _{u}\cdot\sigma _{v}\cdot \rho +a^{2}\cdot \sigma _{v}^{2},\end{eqnarray}
где  $\rho $ - коэффициент канонической корреляции между каноническими переменными  $u,v$; $\sigma _{u},\sigma _{v}$ - стандартные отклонения канонических переменных  $U,V$  соответственно.

Найдем, когда достигается минимум  $M((u-a\cdot v)^{2})$ для заданного $a$:
    $$\frac{\partial(\sigma _{u}^{2}-2\cdot a\cdot \sigma _{u}\cdot\sigma _{v}\cdot \rho +a^{2}\cdot \sigma _{v}^{2})}{\partial a}=-2\cdot \sigma _{u}\cdot\sigma _{v}\cdot \rho+2a\sigma _{v}^{2}=0$$

$$\rho=\frac{a\sigma_v}{\sigma_u}$$

В этом случае ошибка достигает значения:
$$\sigma _{u}^{2}-2\cdot a\cdot \sigma _{u}\cdot\sigma _{v}\cdot \frac{a\sigma_v}{\sigma_u} +a^{2}\cdot \sigma _{v}^{2}=\sigma _{u}^{2}-a^2\sigma_v^2=\sigma_u^2(1-\rho^2)$$

Из последнего видно, что чем больше $\rho$, тем точнее можно описать величину $u$ через величину $v$ линейной зависимостью.

Для нахождения векторов  $\alpha =(\alpha _{1},\alpha _{2},\ldots,\alpha _{n})$ и  $\beta =(\beta _{1},\beta _{2},\ldots ,\beta _{m})$ выразим коэффициент корреляции между каноническими переменными  $u,v$:
 $$\rho =\frac{\mathit{cov}(U,V)}{\sigma _{u}\cdot \sigma _{v}}$$
Обозначим:

 $R_{\mathit{PP}}=P^T\cdot P$ - ковариационная матрица факторов  $P$;

 $R_{\mathit{WW}}=W^T\cdot W$- ковариационная матрица показателей $W$;

 $R_{\mathit{PW}}=P^T\cdot W$- кросс ковариационная матрица между  $P$  и $W$.

получим:
$$\rho =\frac{\mathit{cov}(\alpha \cdot P^{T},\beta \cdot W^{T})}{\sigma_{u}\cdot \sigma _{v}}=\frac{\alpha \cdot P^{T}\cdot (\beta\cdot W^T)^T}{\sigma_{u}\cdot \sigma _{v}}=\frac{\alpha \cdot P^{T}\cdot W\cdot \beta^T}{\sigma_{u}\cdot \sigma _{v}}$$

С учетом введенных обозначений:
\begin{eqnarray}\label{m_f5}\nonumber\frac{\alpha \cdot \mathit{cov}(P,W)\cdot \beta ^{T}}{\sigma _{u}\cdot\sigma _{v}}=\\\
  \frac{\alpha \cdot R_{\mathit{PW}}\cdot \beta^{T}}{\sqrt{\alpha \cdot R_{\mathit{PP}}\cdot \alpha ^{T}}\cdot\sqrt{\beta \cdot R_{\mathit{WW}}\cdot \beta ^{T}}}\end{eqnarray}
Введем также обозначения:
 $$\begin{eqnarray}\label{m_f6}c=\sqrt{R_{\mathit{PP}}}\cdot \alpha^{T},d=\sqrt{R_{\mathit{WW}}}\cdot \beta ^{T},\end{eqnarray}$$
откуда 

 $$\begin{eqnarray}\label{m_f7}\alpha =c^{T}\cdot (R_{\mathit{PP}})^{-1/2},\end{eqnarray}$$
 $$\begin{eqnarray}\label{m_f8}\beta ^{T}=(R_{\mathit{WW}})^{-1/2}\cdot d\end{eqnarray}$$
Тогда 
 $$\begin{eqnarray}\label{m_f9}\nonumber\frac{\alpha \cdot R_{\mathit{PW}}\cdot \beta ^{T}}{\sqrt{\alpha \cdot R_{\mathit{PP}}\cdot \alpha ^{T}}\cdot \sqrt{\beta \cdot R_{\mathit{WW}}\cdot \beta ^{T}}}=\\\frac{c^{T}\cdot (R_{\mathit{PP}})^{-1/2}\cdot {R_{\mathit{PW}}}\cdot (R_{\mathit{WW}})^{-1/2}\cdot d}{\sqrt{c^{T}\cdot c\cdot d^{T}\cdot d}}\end{eqnarray}$$

Рассмотрим выражение
$$\begin{eqnarray}\label{m_f10}\nonumber G\cdot G^{T}=(c^{T}\cdot (R_{\mathit{PP}})^{-1/2}\cdot{R_{\mathit{PW}}}\cdot (R_{\mathit{WW}})^{-1/2})\cdot \\\ \nonumber (c^{T}\cdot(R_{\mathit{PP}})^{-1/2}\cdot {R_{\mathit{PW}}}\cdot(R_{\mathit{WW}})^{-1/2})^{T}\\\
G\cdot G^{T}=g_{1}^{2}+g_{2}^{2}+\ldots+g_{m}^{2}\end{eqnarray}$$
а также
 $$d^{T}\cdot d=d_{1}^{2}+d_{2}^{2}+\ldots +d_{m}^{2}$$
Используя неравенство Коши-Шварца, имеем:
$$\begin{equation*}
\sqrt{(g_{1}^{2}+g_{2}^{2}+\ldots q_{m}^{2})\cdot(d_{1}^{2}+d_{2}^{2}+\ldots d_{m}^{2})}\geqslant g_{1}\cdot d_{1}+g_{2}\cdot d_{2}+\ldots g_{m}\cdot d_{m}
\end{equation*}$$
или  $\sqrt{G\cdot G^{T}\cdot d^{T}\cdot d}\geqslant G\cdot d$. 

Поэтому
 $$\begin{eqnarray}\label{m_f11}\nonumber \rho =\frac{c^{T}\cdot (R_{\mathit{PP}})^{-1/2}\cdot{R_{\mathit{PW}}}\cdot (R_{\mathit{WW}})^{-1/2}\cdot d}{\sqrt{c^{T}\cdot c\cdot d^{T}\cdot d}}=\frac{G\cdot d}{\sqrt{c^{T}\cdot c\cdot d^{T}\cdot d}}\leqslant  \frac{\sqrt{G\cdot G^{T}\cdot d^{T}\cdot d}}{\sqrt{c^{T}\cdot c\cdot d^{T}\cdot d}}=\frac{\sqrt{G\cdot G^{T}}}{\sqrt{c^{T}\cdot c}}\end{eqnarray}$$
Окончательно выражение можно переписать в виде:
$$ \begin{eqnarray}\label{m_f12}\rho \leqslant \frac{\sqrt{c^{T}\cdot (R_{\mathit{PP}})^{-1/2}\cdot R_{\mathit{PW}}\cdot (R_{\mathit{WW}})^{-1}\cdot {R_{WP}}\cdot (R_{\mathit{PP}})^{-1/2}\cdot c}}{\sqrt{c^{T}\cdot c}}\end{eqnarray}$$

Если в качестве  $c$ взять собственный вектор матрицы  
$$(R_{\mathit{PP}})^{-1/2}\cdot R_{\mathit{PW}}\cdot (R_{\mathit{WW}})^{-1}\cdot {R_{WP}}\cdot (R_{\mathit{PP}})^{-1/2},$$ 
то  $$(R_{\mathit{PP}})^{-1/2}\cdot R_{\mathit{PW}}\cdot (R_{\mathit{WW}})^{-1}\cdot {R_{WP}}\cdot (R_{\mathit{PP}})^{-1/2}\cdot c=\lambda \cdot c,$$
где  $\lambda $ - собственное значение, соответствующее собственному вектору  $c,$  тогда
$$ \begin{eqnarray}\label{m_f13}\rho \leqslant \frac{\sqrt{c^{T}\lambda \cdot c}}{\sqrt{c^{T}\cdot c}}=\sqrt{\lambda }\end{eqnarray}$$

Зная  $c$, можно найти искомый вектор  $\alpha =(\alpha _{1},\alpha _{2},\ldots ,\alpha _{n})=c^{T}\cdot (R_{\mathit{PP}})^{-1/2}.$

Для нахождения вектора  $\beta $ заметим, что  можно выполнить другую группировку, а именно, взяв в качестве матрицы  $G$ матрицу  $$G'=(R_{\mathit{PP}})^{-1/2}\cdot {R_{\mathit{PW}}}\cdot (R_{\mathit{WW}})^{-1/2}\cdot d$$  и рассмотрев произведение  $$(G')^{T}\cdot G'=d^{T}\cdot (R_{\mathit{WW}})^{(-1/2)}\cdot R_{WP}\cdot R_{\mathit{PP}}^{-1}\cdot R_{\mathit{PW}}\cdot (R_{\mathit{WW}})^{-1/2}\cdot d$$

Тогда в качестве  $d$ следует взять собственный вектор матрицы  $$(R_{\mathit{WW}})^{(-1/2)}\cdot R_{WP}\cdot R_{\mathit{PP}}^{-1}\cdot R_{\mathit{PW}}\cdot (R_{\mathit{WW}})^{-1/2}$$ после чего можно выразить искомый вектор $\beta =(\beta _{1},\beta _{2},\ldots ,\beta _{m})=d^T\cdot (R_{WW})^{1/2}$.

Поскольку для матрицы  $$(R_{\mathit{PP}})^{-1/2}\cdot R_{\mathit{PW}}\cdot (R_{\mathit{WW}})^{-1}\cdot {R_{WP}}\cdot (R_{\mathit{PP}})^{-1/2}$$  существует несколько собственных векторов, отличающихся величиной собственного значения, то в практике использования канонического корреляционного анализа находят  $\mathit{min}(n,m)$ собственных векторов с последовательно убывающими собственными значениями, что соответствует группе канонических переменных:  $$\{(U_{1},V_{1}),(U_{2},V_{2}),\ldots,(U_{\mathit{min}(n,m)},V_{\mathit{min}(n,m)})\}$$ с соответствующими
последовательно убывающими каноническими корреляциями:  $$\{\rho_{1},\rho _{2},\ldots ,\rho _{\mathit{min}(n,m)}\}$$ Причем за счет ортогональности собственных векторов выполнено условие:
 $$\mathit{cor}(U_{i},U_{j})=\mathit{cor}(V_{i},V_{j})=0,i\neq j$$
Чем больше канонические корреляции, тем сильнее связаны группы показателей  $P$  и   $W$ . 

Поэтому естественным образом возникает вопрос проверки значимости канонических переменных. Для этой цели в теории канонического корреляционного анализа традиционно используют критерий Пирсона  $\chi^{2}$. Если вычислено  $s=\mathit{min}(n,m)$  канонических корреляций  $\rho _{1}<\rho _{2}<\ldots <\rho _{s}$ , то выдвигаются  $s$ нулевых гипотез:
 $$H_{0j}:\rho _{j}=0,j=1,...,s$$
При проверке гипотез статистика  $\chi^{2}$  вычисляется по формуле:
$$ \begin{eqnarray}\label{m_f14} \chi_{j}^{2}=(k-j-\frac{1}{2}\cdot (m+n+1)+\sum _{l=1}^{j-1}\rho_{l}^{2})\cdot \ln \prod _{h=j}^{s}(1-\rho _{h}^{2}), \end{eqnarray}$$
где  $k$ - объем исходной выборки (на практике целесообразно использовать выборки  $k>200$, на выборках  $k<50$  может быть определена лишь сильная каноническая корреляция); $n$  - количество влияющих факторов ; $m$  - количество результативных показателей; $\rho _{l},\rho _{h}$ -  оценки  $l,h$-го коэффициента канонической корреляции. 

Число степеней свободы статистики равно  $(n-j+1)\cdot (m-j+1)$. Если значение статистики превосходит критическое значение при заданном уровне значимости  $\alpha $, или  достигнутый уровень значимости  $p$ не превосходит  $\alpha $ , то данные противоречат гипотезе  $H_{0j}:\rho _{j}=0$  и значит  $\rho _{j}$  отлично от нуля. Если нулевая гипотеза не отвергается для  $\rho _{j}$ , то равны нулю и все последующие канонические корреляции  $\rho _{l}=0,l=j,...,s$ 